version: 'latest'

services:
  # Serviço para a aplicação NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://root:root@nestjs.d9zns.mongodb.net/?retryWrites=true&w=majority&appName=Nestjs
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
